name: Install Solana

inputs:
  solana_version:
    description: Version of Solana to install
    required: true

runs:
  using: 'composite'
  steps:
    - name: Cache Solana Install
      id: cache-solana-install
      uses: actions/cache@v3
      with:
        path: '/home/runner/.local/share/solana/'
        key: ${{ runner.os }}-solana-install-cache-v${{ inputs.solana_version  }}

    - name: Install Solana
      if: steps.cache-solana-install.outputs.cache-hit != 'true'
      run: |
        sh -c "$(curl -sSfL https://release.solana.com/v${{ inputs.solana_version }}/install)"
      shell: bash

    - name: Add Solana bin to Path
      run: |
        echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
      shell: bash

    - name: Verify Solana install
      run: |
        solana --version
      shell: bash
