# Implicit dependencies
# - actions/checkout@v2
# - ./.github/actions/install-linux-build-deps
# - ./.github/actions/install-solana
# - ./.github/actions/install-rust

name: Hydra Integration Dependencies
description: Builds the dependencies for the Hydra integration test
runs:
  using: 'composite'
  steps:
    # Build Rust Programs
    - uses: ./.github/actions/build-hydra
    - uses: ./.github/actions/build-token-metadata

    # Install JS SDK deps
    - uses: ./.github/actions/yarn-install-and-build
      with:
        cache_id: sdk-hydra
        working_dir: ./hydra/js
