name: Integration Dependencies
description: Builds the dependencies for the integration tests

inputs:
  name:
    description: The name of the integration test
    required: true

runs:
  using: 'composite'
  steps:
    # Build and install deps
    - uses: ./.github/actions/integration/fixed-price-sale
      if: ${{ inputs.name == 'fixed-price-sale' }}
    - uses: ./.github/actions/integration/hydra
      if: ${{ inputs.name == 'hydra' }}
    - uses: ./.github/actions/integration/candy-machine-core
      if: ${{ inputs.name == 'candy-machine-core' }}
