edition = "2021"
max_width = 100 
imports_indent = "Block"
imports_layout = "Mixed"
imports_granularity = "Crate"
group_imports = "Preserve"
reorder_imports = true
reorder_modules = true
reorder_impl_items = false
