# Implicit dependencies
# - actions/checkout@v3
# - ./.github/actions/install-linux-build-deps
# - ./.github/actions/install-solana
# - ./.github/actions/install-rust

name: Token Metadata and Metaplex Program Dependencies
description: Builds the Token Metadata and Metaplex programs
runs:
  using: 'composite'
  steps:
    # Build deps
    - uses: ./.github/actions/build-program
      with:
        name: token-metadata

    # Get Metaplex program
    - name: Get Metaplex program
      run: |
        solana program dump p1exdMJcjVao65QdewkaZRUnU6VPSXhus9n2GzWfh98 test-programs/mpl_metaplex.so
      shell: bash

    # Get Token Auth Rules program
    - name: Get Token Auth Rules program
      run: |
        solana program dump auth9SigNpDKz4sJJ1DfCTuZrZNSAgh9sFD3rboVmgg test-programs/mpl_token_auth_rules.so
