# Implicit dependencies
# - actions/checkout@v3
# - ./.github/actions/install-linux-build-deps
# - ./.github/actions/install-solana
# - ./.github/actions/install-rust

name: Metaplex Program Dependency
description: Dumps Metaplex program
runs:
  using: 'composite'
  steps:
    # Get Metaplex program
    - name: Get Metaplex program
      run: |
        mkdir -p ./test-programs
        solana program dump -u https://api.mainnet-beta.solana.com p1exdMJcjVao65QdewkaZRUnU6VPSXhus9n2GzWfh98 test-programs/mpl_metaplex.so
      shell: bash
