name: SDK Dependencies
description: Installs and builds the dependencies for the sdk tests

inputs:
  name:
    description: The name of the sdk test
    required: true

runs:
  using: 'composite'
  steps:
    # Build and install deps
    - uses: ./.github/actions/sdk/hydra
      if: ${{ inputs.name == 'hydra' }}
