name: 'Make version changes'
description: 'Make version changes'
inputs:
  changed-packages:
    description: 'Changed packages - in format of <package>/<type>'
    required: true
  versioning:
    description: 'Versioning command(s)'
    required: true
  branch:
    description: 'Branch to checkout'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.branch }}

    # cache and install cargo release
    - uses: actions/cache@v2
      name: Cache Cargo Release
      id: cache-cargo-release
      with:
        path: |
          ~/.cargo/bin/cargo-release
        key: cargo-release-${{ runner.os }}

    - name: Install Cargo Release
      if: steps.cache-cargo-release.outputs.cache-hit != 'true'
      shell: bash
      run: |
        cargo install cargo-release

    - name: Install dependency packages for script
      # we don't commit *.lock files, so we don't need to require immutable installs. if this isn't set to false,
      # we will get an error like `lockfile would have been modified by this install, which is explicitly forbidden.`
      run: |
        YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn install && yarn add @iarna/toml
      shell: bash

    - name: Make version changes
      uses: actions/github-script@v4
      with:
        script: |
          const script = require('.github/actions/make-version-changes/script.js')
          await script(${{ inputs.changed-packages }}, ${{ inputs.versioning }})
