name: 'Make version changes'
description: 'Make version changes'
inputs:
  changed-packages:
    description: 'Changed packages - in format of <package>/<type>'
    required: true
  versioning:
    description: 'Versioning command(s)'
    required: true
  from-branch:
    description: 'From branch'
    required: true
  from-repository:
    description: 'From full repo name'
    required: true
  to-branch:
    description: 'To branch'
    required: true
  to-repository:
    description: 'To full repo name'
    required: true
  pull-number:
    description:
      'Pull request numeric ID. If this is empty, expect a commit-sha with an associated PR.'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.from-branch }}
        repository: ${{ inputs.from-repository }}

    # cache and install cargo release
    - uses: actions/cache@v2
      name: Cache Cargo Release
      id: cache-cargo-release
      with:
        path: |
          ~/.cargo/bin/cargo-release
        key: cargo-release-${{ runner.os }}

    - name: Install Cargo Release
      if: steps.cache-cargo-release.outputs.cache-hit != 'true'
      shell: bash
      run: |
        cargo install cargo-release

    - name: Install dependency packages for script
      run: npm install -g @iarna/toml && npm link @iarna/toml
      shell: bash

    - name: Make version changes
      uses: actions/github-script@v4
      with:
        script: |
          const script = require('.github/actions/make-version-changes/script.js')
          const change_config = {
            from_repository: '${{ inputs.from-repository }}',
            from_branch: '${{ inputs.from-branch }}',
            to_repository: '${{ inputs.to-repository }}',
            to_branch: '${{ inputs.to-branch }}',
            pull_number: '${{ inputs.pull-number }}'
          }
          await script({github, context, core, glob, io, change_config}, ${{ inputs.changed-packages }}, ${{ inputs.versioning }})

    - name: Cleanup dependency installs
      run: git restore yarn.lock
      shell: bash
