name: Yarn Install and Build

inputs:
  cache_id:
    description: ID to use in order to cache yarn install
    required: true
  working_dir:
    description: Directory in which to perform the yarn tasks
    required: true

description: Installs Yarn Packages and Builds

runs:
  using: composite
  steps:
    - uses: actions/cache@v3
      with:
        path: '**/node_modules'
        key: ${{ inputs.cache_id }}-${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      if: ${{ env.CACHE == 'true' }}

    ##############
    # Build Contract 
    ##############
    - name: Install Root Modules
      run: |
        echo 'Install Root Modules: yarn install'
        yarn install
      working-directory: ./
      shell: bash

    - name: Install modules
      run: yarn install
      working-directory: ${{ inputs.working_dir }}
      shell: bash

    - name: Build TypeScript 
      run: yarn build
      working-directory: ${{ inputs.working_dir }}
      shell: bash
