# Implicit dependencies
# - actions/checkout@v2
# - ./.github/actions/install-linux-build-deps
# - ./.github/actions/install-solana
# - ./.github/actions/install-rust

name: Auctioneer Program Dependencies
description: Builds the dependencies for the Auctioneer program test
runs:
  using: 'composite'
  steps:
    - uses: ./.github/actions/build-token-metadata
    - uses: ./.github/actions/build-auction-house
