ARG BASE_IMAGE=solana-test-validator-base:latest

FROM ${BASE_IMAGE} as build

RUN mkdir /metaplex-program-library/target
RUN mkdir /metaplex-program-library/target/idl
COPY /../target/idl/auction_house.json /metaplex-program-library/target/idl/auction_house.json

WORKDIR /

COPY programs programs
COPY scripts scripts
RUN bash -c "/scripts/setup-validator.sh"

WORKDIR /

# Build minimal runtime image with solana and ledger from previous step
FROM ubuntu:20.04 AS runtime
ENV TZ=GMT
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone  

RUN apt update
RUN apt install curl -y
COPY --from=build /install.sh /install.sh
RUN chmod +x /install.sh 
RUN bash -c /install.sh
ENV PATH="/root/.local/share/solana/install/active_release/bin:$PATH"
COPY --from=build /test-ledger /test-ledger
COPY --from=build /keys /keys

EXPOSE 8899
EXPOSE 8900

CMD ["solana-test-validator"]
