# Implicit dependencies
# - actions/checkout@v2
# - ./.github/actions/install-linux-build-deps
# - ./.github/actions/install-solana
# - ./.github/actions/install-rust

name: Build Token Metadata
runs:
  using: 'composite'
  steps:
    - name: build-token-metadata-program
      working-directory: ./token-metadata/program
      run: |
        cargo +${{ env.RUST_STABLE }} build-bpf --version
        cargo +${{ env.RUST_STABLE }} build-bpf --bpf-out-dir ../../target/deploy/
      shell: bash
