name: Program Build Dependencies
description: Installs and builds the dependencies for the program tests

inputs:
  name:
    description: The name of the program test
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3

    # Build and install deps
    - uses: ./.github/actions/program/auctioneer
      if: ${{ inputs.name == 'auctioneer' }}

    - uses: ./.github/actions/program/token-metadata-and-metaplex
      if: ${{ inputs.name == 'fixed-price-sale' }}

    - uses: ./.github/actions/program/token-metadata-and-metaplex
      if: ${{ inputs.name == 'nft-packs' }}
