name: Integration Candy Machine Core

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always
  SOLANA_VERSION: 1.10.35
  RUST_TOOLCHAIN: stable

jobs:
  changes:
    runs-on: buildjet-4vcpu-ubuntu-2004
    # Set job outputs to values from filter step
    outputs:
      core: ${{ steps.filter.outputs.core }}
      package: ${{ steps.filter.outputs.package }}
      workflow: ${{ steps.filter.outputs.workflow }}
    steps:
    - uses: actions/checkout@v2
    # For pull requests it's not necessary to checkout the code
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          core:
            - 'core/**'
          package:
            - 'candy-machine-core/**'
          workflow:
            - '.github/workflows/integration-candy-machine-core.yml'
  build-and-integration-test-candy-machine-core:
    runs-on: buildjet-4vcpu-ubuntu-2004
    env:
      cache_id: program-candy-machine-core 
    needs: changes
    if: ${{ needs.changes.outputs.core == 'true' || needs.changes.outputs.package == 'true' || needs.changes.outputs.workflow == 'true' }}
    steps:
      # Setup Deps
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install-linux-build-deps
      - uses: ./.github/actions/install-solana
        with: 
          solana_version: ${{ env.SOLANA_VERSION }}
      - uses: ./.github/actions/install-rust
        with: 
          toolchain: ${{ env.RUST_TOOLCHAIN }}

      # Restore Cache from previous build/test
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./rust/target
          key: ${{ env.cache_id }}-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ env.RUSTC_HASH }}

      # Build Rust Program
      - uses: ./.github/actions/build-candy-machine-core
      - uses: ./.github/actions/build-token-metadata

      # Install JS SDK deps
      - uses: ./.github/actions/yarn-install-and-build
        with: 
          cache_id: sdk-candy-machine-core
          working_dir: ./candy-machine-core/js
          build_token_metadata: true
          build_auction_house: true
          build_candy_machine: true

      # Start local validator
      - name: start-local-test-validator
        working-directory: ./candy-machine-core/js
        run: DEBUG=amman* yarn amman:start
      
      # Run integration test
      - name: run-integration-test
        id: run_integration_test
        working-directory: ./candy-machine-core/js
        run: DEBUG=mpl* yarn test

      # Stop local validator
      - name: stop-local-test-validator
        working-directory: ./candy-machine-core/js
        run: yarn amman:stop
