name: Program Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]


jobs:
  program-tests:
    name: "Program: ${{ matrix.node.name }}"
    strategy:
      fail-fast: false
      matrix:
        node:
          - name: "auction-house"
          - name: "auctioneer"
          - name: "bubblegum"
          - name: "candy-machine"
          - name: "fixed-price-sale"
#          - name: "gumdrop"
#          - name: "hydra"
#          - name: "nft-packs"
#          - name: "token-entangler"
#          - name: "token-metadata"

    uses: ./.github/workflows/program-reusable.yml
    with:
      name: ${{ matrix.node.name }}
