name: Program Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
    inputs:
      cache:
        description: 'Use Cached Dependencies'
        required: false
        default: true
      changes:
        description: 'Only run when files change'
        required: false
        default: false

jobs:
  program-tests:
    name: "Program: ${{ matrix.node.name }}"
    strategy:
      fail-fast: false
      matrix:
        node:
#          - name: "auction-house"
          - name: "auctioneer"
          - name: "bubblegum"
            cargo_test: false
          - name: "candy-machine"
            cargo_test: true
#          - name: "fixed-price-sale"
#          - name: "gumdrop"
#          - name: "hydra"
#          - name: "nft-packs"
#          - name: "token-entangler"
#          - name: "token-metadata"

    uses: ./.github/workflows/program-reusable.yml
    with:
      name: ${{ matrix.node.name }}
      cargo_test: ${{ matrix.node.cargo_test == '' || 
        (matrix.node.cargo_test != '' && matrix.node.cargo_test == 123) }}
      cache: ${{ (github.event_name == 'workflow_dispatch' && github.event.workflow_dispatch.inputs.cache == 'true') ||
        (github.event_name != 'workflow_dispatch' && false) }}
# CHANGE `&& false` to `&& true` to default the workflow to use caching.
      changes: ${{ (github.event_name == 'workflow_dispatch' && github.event.workflow_dispatch.inputs.changes == 'true') ||
        (github.event_name != 'workflow_dispatch' && true) }}
# CHANGE `&& true` to `&& false` to default the workflow to run regardless of whether the files changed.
