name: Program Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
    inputs:
      cache:
        description: 'Use Cached Dependencies'
        required: true
        default: true
      changes:
        description: 'Only run when files change'
        required: true
        default: true

jobs:
  program-tests:
    name: "Program: ${{ matrix.node.name }}"
    strategy:
      fail-fast: false
      matrix:
        node:
          - name: "auctioneer"
          - name: "bubblegum"
            cargo_test: false
          - name: "candy-machine"
            cargo_test: true
          - name: "auction-house"
          - name: "fixed-price-sale"
          - name: "gumdrop"
          - name: "hydra"
          - name: "nft-packs"
          - name: "token-entangler"
          - name: "token-metadata"

    uses: ./.github/workflows/program-reusable.yml
    with:
      name: ${{ matrix.node.name }}
      cargo_test: ${{ !contains(matrix.node.cargo_test, 'false') }}
      cache: ${{ contains(github.event.workflow_dispatch.inputs.cache, 'true') }}
      changes: ${{ !contains(github.event.workflow_dispatch.inputs.changes, 'false') }}
