name: Program Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
    inputs:
      cache:
        description: 'Use Cached Dependencies'
        required: false
        default: true
      changes:
        description: 'Only run when files change'
        required: false
        default: false

jobs:
  program-tests:
    name: "Program: ${{ matrix.node.name }}"
    strategy:
      fail-fast: false
      matrix:
        node:
          - name: "auction-house"
            verify_rust: true
            cargo_test: true
          - name: "auctioneer"
            verify_rust: true
            cargo_test: true
          - name: "bubblegum"
            verify_rust: true
            cargo_test: true
          - name: "candy-machine"
            verify_rust: true
            cargo_test: true
          - name: "fixed-price-sale"
            verify_rust: false
            cargo_test: true
          - name: "gumdrop"
            verify_rust: true
            cargo_test: true
          - name: "hydra"
            verify_rust: true
            cargo_test: true
          - name: "nft-packs"
            verify_rust: false
            cargo_test: true
          - name: "token-entangler"
            verify_rust: true
            cargo_test: true
          - name: "token-metadata"
            verify_rust: true
            cargo_test: true

    uses: ./.github/workflows/program-reusable.yml
    with:
      name: ${{ matrix.node.name }}
      verify_rust: ${{ matrix.node.verify_rust }}
      cargo_test: ${{ matrix.node.cargo_test }}
      cache: ${{ (github.event_name == 'workflow_dispatch' && github.event.workflow_dispatch.inputs.cache == 'true') ||
        (github.event_name != 'workflow_dispatch' && false) }}
# CHANGE `&& false` to `&& true` to default the workflow to use caching.
      changes: ${{ (github.event_name == 'workflow_dispatch' && github.event.workflow_dispatch.inputs.changes == 'true') ||
        (github.event_name != 'workflow_dispatch' && true) }}
# CHANGE `&& true` to `&& false` to default the workflow to run regardless of whether the files changed.
