name: SDK Token Entangler

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  id-token: write
  contents: write

jobs:
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      core: ${{ steps.filter.outputs.core }}
      package: ${{ steps.filter.outputs.package }}
    steps:
    - uses: actions/checkout@v2
    # For pull requests it's not necessary to checkout the code
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          core:
            - 'core/**'
          package:
            - 'token-entangler/**'

  build-lint-and-test-token-entangler:
    needs: changes
    if: ${{ needs.changes.outputs.core == 'true' || needs.changes.outputs.package == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/yarn-install-and-verify
        with: 
          cache_id: sdk-token-entangler
          working_dir: ./token-entangler/js
          build_token_metadata: true

  upgrade-version-and-publish-binary:
    needs: changes
    if:
      ${{ (needs.changes.outputs.core == 'true' || needs.changes.outputs.package == 'true') && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    env:
      cache_id: program-token-entangler

    steps:
      - uses: actions/checkout@v2
      - name: Publish updated artifacts to NPM and Github
        uses: ./.github/actions/publish-to-npm
        id: publish-to-npm
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-package-dir: ./token-entangler/js
          commit-sha: ${{ github.sha }}
          branch: ${{ github.ref }}
