name: SDK Token Entangler

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      code: ${{ steps.filter.outputs.code }}
    steps:
    - uses: actions/checkout@v2
    # For pull requests it's not necessary to checkout the code
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          code:
            - 'core/**'
            - 'token-entangler/**'
  build-lint-and-test-token-entangler:
    needs: changes
    if: ${{ needs.changes.outputs.code == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/yarn-install-and-verify
        with: 
          cache_id: sdk-token-entangler
          working_dir: ./token-entangler/js
          build_token_metadata: true
