name: SDK Reusable Test

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      skip_test:
        required: true
        type: boolean
      build_core:
        required: true
        type: boolean
      build_token_metadata:
        required: true
        type: boolean
      build_auction_house:
        required: true
        type: boolean
      build_candy_machine:
        required: true
        type: boolean
      cache:
        required: true
        type: boolean

env:
  CARGO_TERM_COLOR: always
  SOLANA_VERSION: 1.10.40
  RUST_TOOLCHAIN: stable
  CACHE: ${{ inputs.cache }}

jobs:
  changes:
    name: Changes
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      core: ${{ steps.filter.outputs.core }}
      package: ${{ steps.filter.outputs.package }}
      workflow: ${{ steps.filter.outputs.workflow }}
      action: ${{ steps.filter.outputs.action }}
    steps:
      - uses: actions/checkout@v2
      # For pull requests it's not necessary to checkout the code
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            core:
              - 'core/js/**'
            package:
              - '${{ inputs.name }}/js/**'
            workflow:
              - '.github/workflows/sdk-reusable.yml'
            action:
              - '.github/actions/sdk/${{ inputs.name }}/action.yml'

  build-lint-and-test:
    name: Build Lint and Test
    needs: changes
    if: |
      needs.changes.outputs.core == 'true' || 
      needs.changes.outputs.package == 'true' || 
      needs.changes.outputs.workflow == 'true' || 
      needs.changes.outputs.action == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Build and install deps if needed
      - uses: ./.github/actions/sdk
        with:
          name: ${{ inputs.name }}

      - uses: ./.github/actions/yarn-install-and-verify
        with:
          cache_id: sdk-${{ inputs.name }}
          working_dir: ./${{ inputs.name }}/js
          skip_test: ${{ inputs.skip_test }}
          build_core: ${{ inputs.build_core }}
          build_token_metadata: ${{ inputs.build_token_metadata }}
          build_auction_house: ${{ inputs.build_auction_house }}
          build_candy_machine: ${{ inputs.build_candy_machine }}
